# Generated by Django 3.0.3 on 2020-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steal',
            name='time',
        ),
        migrations.AddField(
            model_name='steal',
            name='date',
            field=models.DateField(null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='steal',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='steal',
            name='location',
            field=models.CharField(max_length=100, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='steal',
            name='number',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='steal',
            name='price',
            field=models.IntegerField(verbose_name='میزان خسارت'),
        ),
        migrations.AlterField(
            model_name='steal',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
